
spring:
  application:
    name: eureka-server
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # Default uses development

server:
  port: ${SERVER_PORT:8761}  # Allows override by environment variable

eureka:
  client:
    # does NOT register itself as a customer
    register-with-eureka: false
    #  DO NOT download logs from other Eureka servers
    fetch-registry: false
    #  Flexible base URL per environment
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
  instance:
    #  Time before eliminating inactive service (common for all)
    lease-expiration-duration-in-seconds: 90
